#include "pch.h"

#include "AmpereMfgLoader.h"

#include <Config.h>
#include <State.h>
#include <Util.h>
#include <misc/IdentifyGpu.h>
#include <proxies/Ntdll_Proxy.h>

#include <fstream>
#include <sstream>

#ifndef NV_GPU_ARCHITECTURE_GA100
#define NV_GPU_ARCHITECTURE_GA100 0x00000170
#endif

namespace AmpereMfgLoader
{
namespace
{
Status s_status;
bool s_setupAttempted = false;
} // namespace

const Status& LastStatus()
{
    return s_status;
}

std::string GenerateIniContent()
{
    auto* cfg = Config::Instance();
    int maxFrames = cfg->FGDLSSGAmpereMfgMaxFrames.value_or_default();
    if (maxFrames < 0 || maxFrames > 3)
        maxFrames = 3;

    std::string kernelImg = cfg->FGDLSSGAmpereMfgKernelImage.value_or("Auto");
    if (kernelImg != "PTX" && kernelImg != "Cubin")
        kernelImg = "Auto";

    std::ostringstream ss;
    ss << "; Generated by OptiScaler from user configuration\n";
    ss << "[General]\n";
    ss << "Enabled=1\n\n";
    ss << "[FrameGeneration]\n";
    ss << "MaxGeneratedFrames=" << maxFrames << "\n\n";
    ss << "[Logging]\n";
    ss << "Level=2\n";
    ss << "File=1\n";
    ss << "DebugOutput=0\n";
    ss << "EvaluateEvery=120\n";
    ss << "Directory=dlssg_sm86\\logs\n\n";
    ss << "[Debug]\n";
    ss << "MarkGeneratedFrames=0\n";
    ss << "MarkerX=8\n";
    ss << "MarkerY=8\n";
    ss << "MarkerScale=2\n\n";
    ss << "[Compatibility]\n";
    ss << "KernelImage=" << kernelImg << "\n";
    ss << "ForceSM86Route=0\n";
    ss << "SimulateAmpere=0\n\n";
    ss << "[Runtime]\n";
    ss << "Mode=Bundled\n";
    ss << "CacheDirectory=\n";
    ss << "Path=\n\n";
    ss << "[Backends]\n";

    return ss.str();
}

void TrySetup()
{
    if (s_setupAttempted)
        return;
    s_setupAttempted = true;

    auto* cfg = Config::Instance();
    if (!cfg->FGDLSSGAmpereMfgUnlock.value_or_default())
        return;

    s_status.Enabled = true;

    // Mutual exclusion: fail if Ada MFG unlock is also enabled
    if (cfg->FGDLSSGAdaMfgUnlock.value_or_default())
    {
        s_status.ErrorMessage = "Cannot enable Ampere SM86 MFG while Ada (RTX 40) MFG unlock is enabled.";
        LOG_ERROR("AmpereMfgLoader: {}", s_status.ErrorMessage);
        return;
    }

    // GPU guard: verify Nvidia Ampere architecture
    const auto& gpu = IdentifyGpu::getPrimaryGpu();
    if (gpu.vendorId != VendorId::Nvidia)
    {
        s_status.ErrorMessage = "Ampere SM86 MFG requires an NVIDIA GPU.";
        LOG_ERROR("AmpereMfgLoader: {}", s_status.ErrorMessage);
        return;
    }

    const bool isAmpere = (gpu.nvidiaArchInfo.architecture_id == NV_GPU_ARCHITECTURE_GA100) ||
                          ((gpu.nvidiaArchInfo.architecture_id & 0xFFF0) == 0x0170);
    if (!isAmpere)
    {
        s_status.ErrorMessage = std::format(
            "Ampere SM86 MFG requires an RTX 30 series (Ampere) GPU. Detected arch 0x{:x}.",
            static_cast<uint32_t>(gpu.nvidiaArchInfo.architecture_id));
        LOG_ERROR("AmpereMfgLoader: {}", s_status.ErrorMessage);
        return;
    }

    // Locate dlssg_sm86.dll
    auto basePath = Util::DllPath().parent_path();
    auto dllPath = basePath / L"dlssg_sm86" / L"dlssg_sm86.dll";
    if (!std::filesystem::exists(dllPath))
    {
        // Fallback: check directly beside OptiScaler DLL
        auto fallbackPath = basePath / L"dlssg_sm86.dll";
        if (std::filesystem::exists(fallbackPath))
        {
            dllPath = fallbackPath;
        }
        else
        {
            s_status.DllFound = false;
            s_status.ErrorMessage = "dlssg_sm86.dll not found in dlssg_sm86/ subfolder.";
            LOG_ERROR("AmpereMfgLoader: {}", s_status.ErrorMessage);
            return;
        }
    }
    s_status.DllFound = true;

    // Generate and write companion dlssg_sm86.ini beside the DLL
    auto iniPath = dllPath.parent_path() / L"dlssg_sm86.ini";
    try
    {
        std::filesystem::create_directories(iniPath.parent_path());
        std::ofstream iniFile(iniPath, std::ios::out | std::ios::trunc);
        if (!iniFile.is_open())
        {
            s_status.IniWritten = false;
            s_status.ErrorMessage = "Failed to open dlssg_sm86.ini for writing.";
            LOG_ERROR("AmpereMfgLoader: Failed to open {} for writing", wstring_to_string(iniPath.wstring()));
            return;
        }
        iniFile << GenerateIniContent();
        iniFile.close();
        s_status.IniWritten = true;
    }
    catch (const std::exception& ex)
    {
        s_status.IniWritten = false;
        s_status.ErrorMessage = std::string("Error writing dlssg_sm86.ini: ") + ex.what();
        LOG_ERROR("AmpereMfgLoader: Exception writing INI: {}", ex.what());
        return;
    }

    // Load dlssg_sm86.dll
    LOG_INFO("AmpereMfgLoader: Loading {}", wstring_to_string(dllPath.wstring()));
    HMODULE hMod = NtdllProxy::LoadLibraryExW_Ldr(dllPath.c_str(), NULL, 0);
    if (!hMod)
        hMod = LoadLibraryW(dllPath.c_str());

    if (!hMod)
    {
        DWORD err = GetLastError();
        s_status.DllLoaded = false;
        s_status.ErrorMessage = "Failed to load dlssg_sm86.dll (error code " + std::to_string(err) + ").";
        LOG_ERROR("AmpereMfgLoader: Failed to load dlssg_sm86.dll, error: {}", err);
        return;
    }

    s_status.DllLoaded = true;
    s_status.ErrorMessage.clear();
    LOG_INFO("AmpereMfgLoader: SM86 MFG loaded successfully from {}", wstring_to_string(dllPath.wstring()));
}

} // namespace AmpereMfgLoader
